### ISSUE TITLE
Sound Plugin doesn't work

### ISSUE THREAD

**Issue by korean936** [streamer45/mattermost-plugin-voice#11] opened 2020-03-28 18:01 UTC
I tried to install the plugin on Mattermost  5.21.0 running on Ubuntu server 18.04.
The install works fine but when I click on the icone in Mattermost chat I see this but nothing happens, the time still block at 0:00 and the browser doesn't ask autorization for mic.
![image](https://user-images.githubusercontent.com/62809352/77830090-6545f180-7126-11ea-99f6-8406d14e2051.png)

Can you please help?

**Comment by streamer45** [comment] 2020-03-31 12:17
@korean936 

Thank you for the report. I will look into this and let you know.

**Comment by korean936** [comment] 2020-03-31 13:11
@streamer45 Thank you for your work :)

**Comment by streamer45** [comment] 2020-03-31 17:09
@korean936 

I couldn't reproduce this problem so far. Also testing on 5.21.
It would be helpful to know more info about your setup. Browser type and version. Operating system. 
Also the console log output (<kbd>CTRL</kbd>+<kbd>Shift</kbd>+<kbd>i</kbd>) would be extremely useful to figure out what's blocking the recording.

**Comment by korean936** [comment] 2020-04-01 07:33
Hi,

I got this in the console :

```
com.mattermost.voice_5e23551578f984bc_bundle.js:1 Uncaught (in promise) Error: unsupported
    at n._startCapture (com.mattermost.voice_5e23551578f984bc_bundle.js:1)
    at n.start (com.mattermost.voice_5e23551578f984bc_bundle.js:1)
    at Object.startRecording (com.mattermost.voice_5e23551578f984bc_bundle.js:9)
    at com.mattermost.voice_5e23551578f984bc_bundle.js:9
    at Object.e.registerFileUploadMethod.M.id [as action] (com.mattermost.voice_5e23551578f984bc_bundle.js:9)
    at onClick (file_upload.jsx:635)
    at Object.s (react-dom.production.min.js:14)
    at _ (react-dom.production.min.js:15)
    at react-dom.production.min.js:15
    at w (react-dom.production.min.js:17)
```

The server is on : Debian 10 Buster
The client is on : Windows 10 Pro v1909

The browser is : Opera 67.0.3575.115
But I also tried on chrome and firefox, i got the same issue.

**Comment by streamer45** [comment] 2020-04-01 07:35
I believe it might be the same problem as https://github.com/streamer45/mattermost-plugin-voice/issues/4 . Capturing a microphone is not allowed on insecure connections. You need your server to be running on HTTPs.

**Comment by korean936** [comment] 2020-04-01 07:40
Oh ok I didn't notice that
Thank you

**Comment by streamer45** [comment] 2020-04-10 18:25
Closing this since it's not really a bug or something we can fix.

**Closed as completed by streamer45** 2020-04-10 18:25 UTC
Labels: wontfix
