### ISSUE TITLE
Cannot build plugin on Ubuntu 18.04.3

### ISSUE THREAD

**Issue by 143mailliw** [streamer45/mattermost-plugin-voice#2] opened 2019-08-13 21:03 UTC
Build Log:
```mkdir -p dist && \
mkdir -p public && \
cd dist && \
curl -L -o ""mp3enc-wasm-"0.1.6"".tar.gz" -C - "https://github.com/streamer45/mp3rec-wasm/releases/download/v"0.1.6"/"mp3enc-wasm-"0.1.6"".tar.gz" 2> /dev/null && \
cd ../public && \
tar xf ../dist/"mp3enc-wasm-"0.1.6"".tar.gz 2> /dev/null && \
mv "mp3enc-wasm-"0.1.6""/* . && \
mv recorder.js ../webapp/src/client/ && \
rm -rf "mp3enc-wasm-"0.1.6""
Makefile:105: recipe for target 'mp3-wasm' failed
make: *** [mp3-wasm] Error 33
```

Versions:
Ubuntu 18.04.3
Node: 8.10.0
Go: 1.10.4
GNU Make: 4.1

**Comment by streamer45** [comment] 2019-08-13 21:09
Looking into this, couldn't reproduce on Arch.

**Comment by streamer45** [comment] 2019-08-14 14:58
I could reproduce the issue on Ubuntu 18.04.2
It appears to be a problem with older versions of [curl](https://curl.haxx.se/) (version tested 7.58.0) failing if the downloaded file already exists.

**Comment by criticalmiind** [comment] 2019-10-22 12:26
Nice

**Comment by streamer45** [comment] 2020-03-31 12:18
Closing as wontfix for now.

**Closed as completed by streamer45** 2020-03-31 12:18 UTC
Labels: wontfix
